apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ifxj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ifxj
    app.kubernetes.io/part-of: tkrw-pr714-0075-0075-app
  name: devfile-sample-ifxj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ifxj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ifxj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0075-tenant/tkrw-pr714-0075-0075-app/devfile-sample-ifxj@sha256:e6ffd17fe526643c8fd65329e40392fb6c778ad205cc28f1be7784a132b7cc18
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
